# Generated by Django 5.2.1 on 2025-06-07 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_machine_options'),
        ('maintenance', '0003_alter_maintenance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.ForeignKey(limit_choices_to={'name': 'Вид ТО'}, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='machines.handbook'),
        ),
    ]
