# Generated by Django 5.2.1 on 2025-05-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='failure_node',
            field=models.ForeignKey(limit_choices_to={'name': 'Узел отказа'}, on_delete=django.db.models.deletion.PROTECT, related_name='failure_complaints', to='machines.handbook'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_complaints', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='recovery_method',
            field=models.ForeignKey(limit_choices_to={'name': 'Способ восстановления'}, on_delete=django.db.models.deletion.PROTECT, related_name='recovery_complaints', to='machines.handbook'),
        ),
    ]
