# Generated by Django 5.2.1 on 2025-05-27 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'role': 'SO'}, on_delete=django.db.models.deletion.PROTECT, related_name='handled_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
