# Generated by Django 5.2.1 on 2025-05-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-failure_date'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
    ]
