# Generated by Django 5.2.1 on 2025-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=100, unique=True)),
                ('engine_number', models.CharField(max_length=100)),
                ('transmission_number', models.CharField(max_length=100)),
                ('drive_axle_number', models.CharField(max_length=100)),
                ('steering_axle_number', models.CharField(max_length=100)),
                ('supply_contract', models.CharField(blank=True, max_length=100)),
                ('shipping_date', models.DateField()),
                ('consignee', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('equipment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('name', 'title')},
            },
        ),
    ]
