# Generated by Django 5.2.1 on 2025-05-27 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CL'}, on_delete=django.db.models.deletion.PROTECT, related_name='client_owned_machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drive_axle_machines', to='machines.handbook'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(limit_choices_to={'name': 'Модель двигателя'}, on_delete=django.db.models.deletion.PROTECT, related_name='machine_engines', to='machines.handbook'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(limit_choices_to={'name': 'Модель техники'}, on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='machines.handbook'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'role': 'SO'}, on_delete=django.db.models.deletion.PROTECT, related_name='service_maintained_machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steering_axle_machines', to='machines.handbook'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(limit_choices_to={'name': 'Модель трансмиссии'}, on_delete=django.db.models.deletion.PROTECT, related_name='transmission_machines', to='machines.handbook'),
        ),
    ]
