# Generated by Django 5.2.1 on 2025-05-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-shipping_date'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
    ]
